### ISSUE TITLE
Add linting to the project

### ISSUE THREAD

**Issue by rwnx** [rwnx/praisebot#5]
* Establish a canonical formattings style and linter (Black?)
* capture version (some format like dev-requirements.txt: do not put this in the main requirements.txt otherwise piku will install it on deploy)
* Add documentation for running the linter
* Run the linter on the project (and commit the result)

**Comment by yorublaireau** [comment]
I'll pick that as well.

What are your thoughts on adding a pre-commit hook to run the linter?

**Comment by rwnx** [comment]
pre-commit hook seems like a really good idea, so long as it recieves documentation i.e. how to enable and disable it.

I suspect we'll put the linting in a CI PR workflow eventually, but not here.
