### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by rwnx** [rwnx/praisebot#7]
Add a CHANGELOG.md file in the keepachangelog format. 

See example here: https://github.com/rwnx/pynonymizer/blob/master/CHANGELOG.md

**Comment by yorublaireau** [comment]
Your example has versioning, which this repo does not. How do you want to handle that? Should we add versioning to the repo?

**Comment by rwnx** [comment]
Just put everything in "unreleased" for now - we'll handle versioning when we ship the first version. it's likely to happen after #8
